apiVersion: apps/v1
kind: Deployment
metadata:
  name: devportal-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devportal
  template:
    metadata:
      labels:
        app: devportal
    spec:
      containers:
        - name: devportal
          image: iregistry.eur.ad.sag/kub-sic/devportal:10.15
          env:
            - name: SPRING_ELASTICSEARCH_REST_URIS
              value: "http://elasticsearch-service:9200"
          ports:
            - containerPort: 8083

---

apiVersion: v1
kind: Service
metadata:
  name: devportal-service
spec:
  selector:
    app: devportal
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8083
  type: NodePort
